version: "3.8"

services:
  docling-pdf-processor:
    build: .
    container_name: docling-pdf-processor
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=False
      - SECRET_KEY=change-this-in-production
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    restart: unless-stopped
